name: cheq_gallery_app
description: Free gallery app for all
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  data:
    path: ./data/
  device_info_plus: ^11.2.0
  domain:
    path: ./domain/
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.2
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0

  intl: ^0.19.0
  logging: ^1.3.0
  permission_handler: ^11.3.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.14


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


